name: .NET Build, Test and Publish

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Adding this at the top level gives these permissions to all jobs
permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        dotnet restore ActiveSense.Desktop/ActiveSense.Desktop.sln
      
    - name: Build
      run: |
        dotnet build ActiveSense.Desktop/ActiveSense.Desktop.sln --no-restore
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/
          **/obj/
        retention-days: 1
        
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
      
    - name: Test
      run: |
        dotnet test ActiveSense.Desktop/ActiveSense.Desktop.sln --no-build --verbosity normal
      env:
        R_HOME: ${{ runner.temp }}/R

  publish:
    name: Publish
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux-x64
            name: linux
            extension: ""
          - os: win-x64
            name: windows
            extension: ".exe"
          - os: osx-x64
            name: macos
            extension: ""
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Publish ${{ matrix.name }}
      run: |
        dotnet publish ActiveSense.Desktop/ActiveSense.Desktop.csproj \
          -c Release \
          -r ${{ matrix.os }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          -o ./publish/${{ matrix.name }}
    
    - name: Create archive for ${{ matrix.name }}
      run: |
        cd publish
        tar -czf ActiveSense-${{ matrix.name }}.tar.gz ${{ matrix.name }}
    
    - name: Upload ${{ matrix.name }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActiveSense-${{ matrix.name }}
        path: publish/ActiveSense-${{ matrix.name }}.tar.gz
        retention-days: 7

  release:
    name: Create Release
    needs: publish
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: ActiveSense-linux
        path: ./artifacts
    
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: ActiveSense-windows
        path: ./artifacts
    
    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: ActiveSense-macos
        path: ./artifacts
    
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    
    - name: Create Release with GitHub CLI
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Install GitHub CLI if not already installed
        if ! command -v gh &> /dev/null; then
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh
        fi
        
        # Check if the release already exists and delete it if it does
        RELEASE_TAG="release-${{ steps.date.outputs.date }}"
        if gh release view "$RELEASE_TAG" &>/dev/null; then
          echo "Release $RELEASE_TAG already exists. Deleting it..."
          gh release delete "$RELEASE_TAG" --yes
        fi
        
        # Create a new release
        gh release create "$RELEASE_TAG" \
          --title "ActiveSense Release ${{ steps.date.outputs.date }}" \
          --notes "Automated release built on ${{ steps.date.outputs.date }}" \
          ./artifacts/*.tar.gz
