name: .NET Build and Test
on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        dotnet restore ActiveSense.Desktop/ActiveSense.Desktop.sln
      
    - name: Build
      run: |
        dotnet build ActiveSense.Desktop/ActiveSense.Desktop.sln --no-restore -c Debug
        
    - name: Test
      run: |
        dotnet test ActiveSense.Desktop/ActiveSense.Desktop.sln --no-build --verbosity normal
      env:
        R_HOME: ${{ runner.temp }}/R
