name: .NET Build, Test and Publish

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Adding this at the top level gives these permissions to all jobs
permissions:
  contents: write
  packages: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: |
        dotnet restore ActiveSense.Desktop/ActiveSense.Desktop.sln
      
    - name: Build
      run: |
        dotnet build ActiveSense.Desktop/ActiveSense.Desktop.sln --no-restore
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/bin/
          **/obj/
        retention-days: 1
        
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
      
    - name: Test
      run: |
        dotnet test ActiveSense.Desktop/ActiveSense.Desktop.sln --no-build --verbosity normal
      env:
        R_HOME: ${{ runner.temp }}/R
        
  publish:
    name: Publish All Platforms
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Make package scripts executable
      run: |
        chmod +x Package/linux/package.sh
        chmod +x Package/windows/package.sh
        chmod +x Package/macos/package.sh
    
    - name: Create output directories
      run: |
        mkdir -p publish/linux
        mkdir -p publish/windows
        mkdir -p publish/macos
    
    - name: Run Linux package script
      run: ./Package/linux/package.sh
    
    - name: Run Windows package script
      run: ./Package/windows/package.sh
      
    - name: Run macOS package script
      run: ./Package/macos/package.sh
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActiveSense-linux
        path: publish/ActiveSense-linux.tar.gz
        retention-days: 7
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActiveSense-windows
        path: publish/ActiveSense-windows.tar.gz
        retention-days: 7
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: ActiveSense-macos
        path: publish/ActiveSense-macos.tar.gz
        retention-days: 7
