name: Build Cross-Platform Installers
on:
  push:
    branches: [ main, rscript/precompiled-dependencies-workflow ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, rscript/precompiled-dependencies-workflow ]
  workflow_dispatch: 

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile is.exe
          Start-Process -FilePath .\is.exe -Args "/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-" -Wait
          Remove-Item .\is.exe
        shell: pwsh
      
      - name: Build Windows Installer
        run: |
          cd ActiveSense.Desktop
          . .\Publish\windows\package.ps1
        shell: pwsh
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          name: ActiveSense Dave
          draft: true
          prerelease: false
          files: |
            ActiveSense.Desktop/Publish/windows/ActiveSense-Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Build Linux Installer
        run: |
          cd ActiveSense.Desktop
          chmod +x Publish/linux/package-linux.sh
          ./Publish/linux/package-linux.sh
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          name: ActiveSense Dave
          draft: true
          prerelease: false
          files: |
            ActiveSense.Desktop/Publish/linux/ActiveSense-Linux-Installer.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      
      - name: Build macOS Installer
        run: |
          cd ActiveSense.Desktop
          chmod +x Publish/macos/package-dmg.sh
          ./Publish/macos/package-dmg.sh
      
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          name: ActiveSense Dave
          draft: true
          prerelease: false
          files: |
            ActiveSense.Desktop/Publish/macos/ActiveSense-Installer.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
