name: Run R Script Tests on Windows

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ActiveSense.RScripts/**.R'
      - '.github/workflows/r-script-tests.yml'

jobs:
  run-r-script-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Run testthat tests
        run: |
          # This command assumes 'ActiveSense.RScripts/testing/tests.R'
          # is a single R file containing your test_that() calls.
          Rscript -e "testthat::test_file('ActiveSense.RScripts/testing/tests.R', reporter = 'check')"